---
# fast.ru-7a.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast.ru-7a
provisioner: cinder.csi.openstack.org
parameters:
  type: fast.ru-7a
  availability: ru-7a
allowVolumeExpansion: true
