# nginx-nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: webservice
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: webservice
